### ISSUE TITLE
explicitly providing timestamp instead of using walltime

### ISSUE THREAD

**Issue by geertbrit** [solzimer/swstats#1]
I'm looking to get sliding stats on historic events which have timestamps associated with them. I'd like to use the event timestamps instead of walltime to bucket the events. Is this possible in any way?

**Comment by solzimer** [comment]
Hi @gebrits,

The current implementation does not provide a way to provide external/relative timestamps, but it's something that looks interesting. I'll take a look to provide an implementation, as it's easily doable.

**Comment by solzimer** [comment]
Hi @gebrits,

I have updated the TimeStats window so it can run in "relative" timestamp mode. You must initialize the window with the option "timestamp":

```javascript
// Time window of 10 seconds with relative timestamp
var tw2 = new SWindow.TimeStats(10000,{
	timestamp:TimeStats.TS.RELATIVE,
	step:1000,      // Values will be accumulated in slots of 1 second
	type:"numeric" // Numeric values
});
```
Then, can pass values as an object with a timestamp and a value:

```javascript
tw2.push({ts:1517499913578 ,v:10});
```
Timestamps can be provided as simple relative numbers (ex: number of milliseconds, Date.now()), or directly as javascript Date objects.

Let me know if it's working for you, so I can close the issue

**Comment by geertbrit** [comment]
Cheers for that! Can't wait to check it out :)
